name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore .\OmnifinNative\OmnifinNative.csproj -r win-x64

      - name: Check formatting and analyzers
        run: dotnet format .\OmnifinNative\OmnifinNative.csproj --verify-no-changes --no-restore

      - name: Build project
        run: dotnet build .\OmnifinNative\OmnifinNative.csproj -c Release -r win-x64 --no-restore -warnaserror /p:PublishReadyToRun=false
